apiVersion: v1
kind: Service
metadata:
  name: go-app-svc
  namespace: go-test
  labels:
    app: go
    name: go-app-svc
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      protocol: TCP
#    - port: 17701
#      name: metrics
#      protocol: TCP
  selector:
    app: go
  type: LoadBalancer
